### ISSUE TITLE
broken in CE 1.9.2.2

### ISSUE THREAD

**Issue by akkermanronald** [etailer/Etailer_Backorders#1]
Fantastic piece of work, but unfortunately the module seems to be broken in Magento 1.9.2.2.

See screenshot below:

<img width="594" alt="schermafdruk 2015-12-05 18 59 58" src="https://cloud.githubusercontent.com/assets/15016164/11609258/79fe4006-9b82-11e5-9e91-af03d3212e4a.png">

Any chance you could have a look at this? No problem to contribute to the cost of module development.

Regards
Ronald

**Comment by rjocoleman** [comment]
@akkermanronald 

what are the steps to reproduce this?

**Comment by akkermanronald** [comment]
Hi Robert,

I have tried on a fresh 1.9.2.2 install just now but unable to replicate the issue.

We will investigate further to try and find out what causes this issue and will revert back to you. I have just tried to create a new item manually on the instance that gives the failure message, but I am unable to save the product, with the same failure message as posted on Github.

Any suggestions or feedback are welcome. I think there maybe a conflict with the module from Ebizmarts used for our iPad POS solution, see also attached for reference.

Regards
Ronald

**Comment by rjocoleman** [comment]
OK - I'm rewriting `Mage_CatalogInventory_Model_Stock_Item` in this extension and the Ebizmarts will be too, this is very likely the cause.

The easiest way to deal with that (which isn't the proper way but it's fast) is to fork this extension.
There are two ways of dealing with this, you'd have to look at the Ebizmarts extension to see if they have a `checkQty` method implemented, if they do _not_ then:
- Add a `<depends>` element to the `/app/etc/modules/Etailer_Backorders.xml` for the Ebizmarts module and it's should resolve the issue.

If there is a conflicting `checkQty` method:
- Add the `<depends>` as above
- Change https://github.com/etailer/Etailer_Backorders/blob/master/app/code/community/Etailer/Backorders/Model/Stock/Item.php#L3 to `class Etailer_Backorders_Model_Stock_Item extends Ebizmarts_Extension_Model_Whatever_They_Called_It`
  You'd need to inspect to make sure the `checkQty` was handled according to what you need.

The other more proper way of handling this is to re-work this extension to not use rewrites - I don't see any clean ways to do this off the top of my head because the core is a bit ugly and unhelpful here.

**Comment by akkermanronald** [comment]
A bit late, but better late than never. There was indeed a conflict with the Ebizmarts POS extension and this has now been resoled by implementing your suggestion.
